export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_FULL_PRODUCT="GET_FULL_PRODUCT"
export const ADD_PRODUCT="ADD_PRODUCT"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"
export const CLEAN_PRODUCT_STATE = "CLEAN_PRODUCT_STATE"
export const GET_PURCHASES="GET_PURCHASES"

export const GET_CART_PRODUCTS="GET_CART_PRODUCTS"
export const ADD_CART_PRODUCT="ADD_CART_PRODUCT"
export const REMOVE_CART_ITEM="REMOVE_CART_ITEM"
export const CLEAN_CART_STATE="CLEAN_CART_STATE"
export const REMOVE_ITEM_FROM_STORAGE="REMOVE_ITEM_FROM_STORAGE"

export const AUTH="AUTH"
export const AUTH_FAIL="AUTH_FAIL"
export const SIGNIN_FAIL="SIGNIN_FAIL"
export const LOGOUT="LOGOUT"
export const AUTH_REQUEST="AUTH_REQUEST"

export const SET_PAYMENT_STATE="SET_PAYMENT_STATE"



